apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-generator
  name: secret-generator
  namespace: hlb-gitops

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-generator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secret-generator
    spec:
      containers:
      - args:
        - while true; do sleep 30; done;
        command:
        - /bin/sh
        - -c
        - --
        image: docker.io/jreitzig/secrets-generator:latest
        imagePullPolicy: Always
        name: secrets-generator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/config.yaml
          name: config
          readOnly: true
          subPath: config.yaml
        - mountPath: /mnt/secret.j2
          name: secret
          readOnly: true
          subPath: secret.j2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: sgconfig
        name: config
      - configMap:
          defaultMode: 420
          name: sgsecret
        name: secret
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
